require 'sinatra'
require 'sinatra/base'
#require 'sinatra/assetpack'
require 'faraday'
require 'haml'
require 'sinatra'
require 'sinatra/base'
require 'active_record'
require "rake"
require 'rack-flash'
require 'sinatra/redirect_with_flash'
helpers Sinatra::RedirectWithFlash
enable :sessions